name: pdf_scanner
description: "PDF scanner"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  For state menegement
  flutter_bloc: ^9.1.1
  # For enabling iOS icon support
  cupertino_icons: ^1.0.8
  # For navigation and routing
  go_router: ^15.1.3
  # For generating launcher icons
  flutter_launcher_icons: ^0.14.3
  # For enabling google fonts
  google_fonts: ^6.2.1
  # For translation support
  easy_localization: ^3.0.7+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Icon_1028.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo2.png
    - assets/images/
    - assets/icons/
    - assets/fonts/
