name: pdf_scanner
description: "PDF scanner"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  For state menegement
  flutter_bloc: ^9.1.1
  # For enabling iOS icon support
  cupertino_icons: ^1.0.8
  # For navigation and routing
  go_router: ^15.1.3
  # For generating launcher icons
  flutter_launcher_icons: ^0.14.3
  # For enabling google fonts
  google_fonts: ^6.2.1
  # For translation support
  easy_localization: ^3.0.7+1
  # For showing rate app window
  rate_my_app: ^2.3.1
  # The ProImageEditor is a Flutter widget designed for image editing within your application.
  pro_image_editor: ^9.11.2
  # For showing pdf files
  cunning_document_scanner: ^1.2.3
  # For crreating icons
  flutter_dynamic_icon: ^2.1.0
  # For showing native splash screen
  flutter_native_splash: ^2.4.6
  # For cache management
  shared_preferences: ^2.5.3
  # For responsive design
  flutter_screenutil: ^5.9.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Icon_1028.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icons/icon_1028.png"
  android: true
  ios: true
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Text-Bold.otf
          weight: 500

  assets:
    - lib/src/core/l10n/codegen_loader.g.dart
    - assets/images/logo2.png
    - assets/images/
    - assets/icons/
    - assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Regular.otf
    - assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Text-Bold.otf
